apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-app
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/clteco-02/cltco-team02
      targetRevision: main
      path: helms/backend
      helm:
        valueFiles:
          - $values/helms/backend/values.yaml
    - repoURL: https://github.com/clteco-02/cltco-team02
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
