apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-ui
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://provectus.github.io/kafka-ui-charts
      chart: kafka-ui
      targetRevision: 0.7.6
      helm:
        valueFiles:
          - $values/helms/kafka-ui/values.yaml
    - repoURL: https://github.com/binary-h0/cltco-team02
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true